disabled = false
languageCode = "en"
languageName = "English"
weight = 1
enableCodeCopy = true
title = "My Personal Website"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "January 2, 2006"
  # logo = "profile_rounded.png"
  secondaryLogo = "profile.jpeg"
  description = "Personal website and portfolio"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Nguyen Trung Kien"
  image = "profile.jpeg"
  email = "admin@suba-server.org"
  headline = "Software Developer | Linux Enthusiast"
  bio = "Software Developer | Linux Enthusiast"
  links = [
    { email = "mailto:admin@suba-server.org" },
    { link = "https://suba-server.org/" },
    { facebook = "https://facebook.com/SubaruLenz" },
    { github = "https://github.com/SubaruLenz" },
    { linkedin = "https://www.linkedin.com/in/nguyetrungkien/" },
    { steam = "https://steamcommunity.com/profiles/SubaruLenz" },
    { whatsapp = "https://wa.me/337047828" },
  ]