baseURL = 'https://suba-server.org'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
theme = 'blowfish'

[languages]
  [languages.en]
    languageCode = 'en-us'
    languageName = 'English'
    title = 'My Personal Website'
    weight = 1
  
  [languages.vi]
    languageCode = 'vi'
    languageName = 'Tiếng Việt'
    title = 'Trang Web Cá Nhân'
    weight = 2
    dateFormat = '2 January 2006'
